
----jOINING 3 TABLES FOR POWER BI DASHBOARD----
WITH HOTELS AS (
SELECT *
FROM DBO.['2018$']
UNION
SELECT *
FROM DBO.['2019$']
UNION
SELECT *
FROM DBO.['2020$'])

SELECT*
FROM HOTELS 
LEFT JOIN DBO.market_segment$
ON HOTELS.market_segment = market_segment$.market_segment
LEFT JOIN DBO.meal_cost$
ON meal_cost$.MEAL = HOTELS.MEAL
GROUP BY HOTEL

---lOOKING AT THE REVENUE ON BOTH OF THE HOTELS FOR 2018,2019,2020---

SELECT
ARRIVAL_DATE_YEAR,
ROUND (SUM((STAYS_IN_WEEK_NIGHTS + STAYS_IN_WEEKEND_NIGHTS)*ADR) ,2)AS REVENUE 
FROM HOTELS 
GROUP BY ARRIVAL_DATE_YEAR

--- 


---iS THE HOTEL REVENUE GROWING BY YEAR?---
----SHOULD WE INCREASE THE PARKING SIZE?---
---WHAT TRENDS CAN WE SEE IN THE DATA---?

---iS THE HOTEL REVENUE GROWING BY YEAR?---

WITH HOTELS AS (
SELECT *
FROM DBO.['2018$']
UNION
SELECT *
FROM DBO.['2019$']
UNION
SELECT *
FROM DBO.['2020$'])


SELECT 
ARRIVAL_DATE_YEAR,
HOTEL,
ROUND (SUM((STAYS_IN_WEEK_NIGHTS + STAYS_IN_WEEKEND_NIGHTS)*ADR) ,2)AS REVENUE 
FROM HOTELS 
GROUP BY ARRIVAL_DATE_YEAR,HOTEL